//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serviceID.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cevap
    {
        public cevap()
        {
            this.begenis = new HashSet<begeni>();
            this.yorums = new HashSet<yorum>();
        }
    
        public int cevapId { get; set; }
        public Nullable<System.DateTime> cevapTarihi { get; set; }
        public string cevap1 { get; set; }
        public int soruId { get; set; }
        public int kullaniciId { get; set; }
    
        public virtual ICollection<begeni> begenis { get; set; }
        public virtual kullanici kullanici { get; set; }
        public virtual soru soru { get; set; }
        public virtual ICollection<yorum> yorums { get; set; }
    }
}
