//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serviceID.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cevap
    {
        public cevap()
        {
            this.kullanicis = new HashSet<kullanici>();
        }
    
        public int cevapId { get; set; }
        public Nullable<int> yorumId { get; set; }
        public Nullable<int> begeniId { get; set; }
        public Nullable<System.DateTime> cevapTarihi { get; set; }
        public string cevap1 { get; set; }
    
        public virtual begeni begeni { get; set; }
        public virtual yorum yorum { get; set; }
        public virtual ICollection<kullanici> kullanicis { get; set; }
    }
}
