//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serviceID.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class favori
    {
        public int favoriId { get; set; }
        public int soruId { get; set; }
        public int kullaniciId { get; set; }
    
        public virtual kullanici kullanici { get; set; }
        public virtual soru soru { get; set; }
    }
}
