//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serviceID.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class idDBEntities : DbContext
    {
        public idDBEntities()
            : base("name=idDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<begeni> begenis { get; set; }
        public DbSet<cevap> cevaps { get; set; }
        public DbSet<etiket> etikets { get; set; }
        public DbSet<favori> favoris { get; set; }
        public DbSet<kategori> kategoris { get; set; }
        public DbSet<kullanici> kullanicis { get; set; }
        public DbSet<soru> sorus { get; set; }
        public DbSet<soruEtiket> soruEtikets { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<yorum> yorums { get; set; }
    }
}
