//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serviceID.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class kategori
    {
        public kategori()
        {
            this.sorus = new HashSet<soru>();
        }
    
        public int kategorId { get; set; }
        public string kategoriAd { get; set; }
    
        public virtual ICollection<soru> sorus { get; set; }
    }
}
