//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serviceID.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanici
    {
        public kullanici()
        {
            this.soruDetays = new HashSet<soruDetay>();
        }
    
        public int kullaniciId { get; set; }
        public Nullable<int> soruId { get; set; }
        public Nullable<int> cevapId { get; set; }
        public string kullaniciAdi { get; set; }
        public string email { get; set; }
        public string sifre { get; set; }
    
        public virtual cevap cevap { get; set; }
        public virtual ICollection<soruDetay> soruDetays { get; set; }
    }
}
