//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serviceID.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanici
    {
        public kullanici()
        {
            this.begenis = new HashSet<begeni>();
            this.cevaps = new HashSet<cevap>();
            this.favoris = new HashSet<favori>();
            this.sorus = new HashSet<soru>();
            this.yorums = new HashSet<yorum>();
        }
    
        public int kullaniciId { get; set; }
        public string kullaniciAdi { get; set; }
        public string email { get; set; }
        public string sifre { get; set; }
    
        public virtual ICollection<begeni> begenis { get; set; }
        public virtual ICollection<cevap> cevaps { get; set; }
        public virtual ICollection<favori> favoris { get; set; }
        public virtual ICollection<soru> sorus { get; set; }
        public virtual ICollection<yorum> yorums { get; set; }
    }
}
