//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serviceID.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class soru
    {
        public soru()
        {
            this.soruDetays = new HashSet<soruDetay>();
        }
    
        public int soruId { get; set; }
        public Nullable<int> kategoriId { get; set; }
        public Nullable<int> etiketId { get; set; }
        public string baslik { get; set; }
        public Nullable<System.DateTime> yayinTarihi { get; set; }
        public Nullable<bool> onayDurumu { get; set; }
        public Nullable<int> favoriId { get; set; }
    
        public virtual etiket etiket { get; set; }
        public virtual favori favori { get; set; }
        public virtual kategori kategori { get; set; }
        public virtual ICollection<soruDetay> soruDetays { get; set; }
    }
}
