//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serviceID.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class soru
    {
        public soru()
        {
            this.cevaps = new HashSet<cevap>();
            this.favoris = new HashSet<favori>();
            this.soruEtikets = new HashSet<soruEtiket>();
        }
    
        public int soruId { get; set; }
        public Nullable<int> kategoriId { get; set; }
        public Nullable<int> etiketId { get; set; }
        public string baslik { get; set; }
        public Nullable<System.DateTime> yayinTarihi { get; set; }
        public Nullable<bool> onayDurumu { get; set; }
        public Nullable<int> kullaniciId { get; set; }
        public string soruIcerik { get; set; }
    
        public virtual ICollection<cevap> cevaps { get; set; }
        public virtual ICollection<favori> favoris { get; set; }
        public virtual kategori kategori { get; set; }
        public virtual kullanici kullanici { get; set; }
        public virtual ICollection<soruEtiket> soruEtikets { get; set; }
    }
}
