//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serviceID.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class yorum
    {
        public yorum()
        {
            this.cevaps = new HashSet<cevap>();
        }
    
        public int yorumId { get; set; }
        public string yorum1 { get; set; }
        public Nullable<System.DateTime> yorumTarihi { get; set; }
    
        public virtual ICollection<cevap> cevaps { get; set; }
    }
}
