//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clientID.idService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="kullanici", Namespace="http://schemas.datacontract.org/2004/07/ServiceID.Model")]
    [System.SerializableAttribute()]
    public partial class kullanici : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.idService.begeni[] begenisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.idService.cevap[] cevapsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.idService.favori[] favorisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kullaniciAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int kullaniciIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sifreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.idService.soru[] sorusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.idService.yorum[] yorumsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.idService.begeni[] begenis {
            get {
                return this.begenisField;
            }
            set {
                if ((object.ReferenceEquals(this.begenisField, value) != true)) {
                    this.begenisField = value;
                    this.RaisePropertyChanged("begenis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.idService.cevap[] cevaps {
            get {
                return this.cevapsField;
            }
            set {
                if ((object.ReferenceEquals(this.cevapsField, value) != true)) {
                    this.cevapsField = value;
                    this.RaisePropertyChanged("cevaps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.idService.favori[] favoris {
            get {
                return this.favorisField;
            }
            set {
                if ((object.ReferenceEquals(this.favorisField, value) != true)) {
                    this.favorisField = value;
                    this.RaisePropertyChanged("favoris");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kullaniciAdi {
            get {
                return this.kullaniciAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.kullaniciAdiField, value) != true)) {
                    this.kullaniciAdiField = value;
                    this.RaisePropertyChanged("kullaniciAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int kullaniciId {
            get {
                return this.kullaniciIdField;
            }
            set {
                if ((this.kullaniciIdField.Equals(value) != true)) {
                    this.kullaniciIdField = value;
                    this.RaisePropertyChanged("kullaniciId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sifre {
            get {
                return this.sifreField;
            }
            set {
                if ((object.ReferenceEquals(this.sifreField, value) != true)) {
                    this.sifreField = value;
                    this.RaisePropertyChanged("sifre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.idService.soru[] sorus {
            get {
                return this.sorusField;
            }
            set {
                if ((object.ReferenceEquals(this.sorusField, value) != true)) {
                    this.sorusField = value;
                    this.RaisePropertyChanged("sorus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.idService.yorum[] yorums {
            get {
                return this.yorumsField;
            }
            set {
                if ((object.ReferenceEquals(this.yorumsField, value) != true)) {
                    this.yorumsField = value;
                    this.RaisePropertyChanged("yorums");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="begeni", Namespace="http://schemas.datacontract.org/2004/07/ServiceID.Model")]
    [System.SerializableAttribute()]
    public partial class begeni : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int begeniIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> begeniTuruIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.idService.cevap cevapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> cevapIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.idService.kullanici kullaniciField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int kullaniciIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int begeniId {
            get {
                return this.begeniIdField;
            }
            set {
                if ((this.begeniIdField.Equals(value) != true)) {
                    this.begeniIdField = value;
                    this.RaisePropertyChanged("begeniId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> begeniTuruId {
            get {
                return this.begeniTuruIdField;
            }
            set {
                if ((this.begeniTuruIdField.Equals(value) != true)) {
                    this.begeniTuruIdField = value;
                    this.RaisePropertyChanged("begeniTuruId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.idService.cevap cevap {
            get {
                return this.cevapField;
            }
            set {
                if ((object.ReferenceEquals(this.cevapField, value) != true)) {
                    this.cevapField = value;
                    this.RaisePropertyChanged("cevap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> cevapId {
            get {
                return this.cevapIdField;
            }
            set {
                if ((this.cevapIdField.Equals(value) != true)) {
                    this.cevapIdField = value;
                    this.RaisePropertyChanged("cevapId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.idService.kullanici kullanici {
            get {
                return this.kullaniciField;
            }
            set {
                if ((object.ReferenceEquals(this.kullaniciField, value) != true)) {
                    this.kullaniciField = value;
                    this.RaisePropertyChanged("kullanici");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int kullaniciId {
            get {
                return this.kullaniciIdField;
            }
            set {
                if ((this.kullaniciIdField.Equals(value) != true)) {
                    this.kullaniciIdField = value;
                    this.RaisePropertyChanged("kullaniciId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="cevap", Namespace="http://schemas.datacontract.org/2004/07/ServiceID.Model")]
    [System.SerializableAttribute()]
    public partial class cevap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.idService.begeni[] begenisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cevap1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cevapIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> cevapTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.idService.kullanici kullaniciField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int kullaniciIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.idService.soru soruField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int soruIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.idService.yorum[] yorumsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.idService.begeni[] begenis {
            get {
                return this.begenisField;
            }
            set {
                if ((object.ReferenceEquals(this.begenisField, value) != true)) {
                    this.begenisField = value;
                    this.RaisePropertyChanged("begenis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cevap1 {
            get {
                return this.cevap1Field;
            }
            set {
                if ((object.ReferenceEquals(this.cevap1Field, value) != true)) {
                    this.cevap1Field = value;
                    this.RaisePropertyChanged("cevap1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cevapId {
            get {
                return this.cevapIdField;
            }
            set {
                if ((this.cevapIdField.Equals(value) != true)) {
                    this.cevapIdField = value;
                    this.RaisePropertyChanged("cevapId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> cevapTarihi {
            get {
                return this.cevapTarihiField;
            }
            set {
                if ((this.cevapTarihiField.Equals(value) != true)) {
                    this.cevapTarihiField = value;
                    this.RaisePropertyChanged("cevapTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.idService.kullanici kullanici {
            get {
                return this.kullaniciField;
            }
            set {
                if ((object.ReferenceEquals(this.kullaniciField, value) != true)) {
                    this.kullaniciField = value;
                    this.RaisePropertyChanged("kullanici");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int kullaniciId {
            get {
                return this.kullaniciIdField;
            }
            set {
                if ((this.kullaniciIdField.Equals(value) != true)) {
                    this.kullaniciIdField = value;
                    this.RaisePropertyChanged("kullaniciId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.idService.soru soru {
            get {
                return this.soruField;
            }
            set {
                if ((object.ReferenceEquals(this.soruField, value) != true)) {
                    this.soruField = value;
                    this.RaisePropertyChanged("soru");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int soruId {
            get {
                return this.soruIdField;
            }
            set {
                if ((this.soruIdField.Equals(value) != true)) {
                    this.soruIdField = value;
                    this.RaisePropertyChanged("soruId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.idService.yorum[] yorums {
            get {
                return this.yorumsField;
            }
            set {
                if ((object.ReferenceEquals(this.yorumsField, value) != true)) {
                    this.yorumsField = value;
                    this.RaisePropertyChanged("yorums");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="favori", Namespace="http://schemas.datacontract.org/2004/07/ServiceID.Model")]
    [System.SerializableAttribute()]
    public partial class favori : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int favoriIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.idService.kullanici kullaniciField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int kullaniciIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.idService.soru soruField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int soruIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int favoriId {
            get {
                return this.favoriIdField;
            }
            set {
                if ((this.favoriIdField.Equals(value) != true)) {
                    this.favoriIdField = value;
                    this.RaisePropertyChanged("favoriId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.idService.kullanici kullanici {
            get {
                return this.kullaniciField;
            }
            set {
                if ((object.ReferenceEquals(this.kullaniciField, value) != true)) {
                    this.kullaniciField = value;
                    this.RaisePropertyChanged("kullanici");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int kullaniciId {
            get {
                return this.kullaniciIdField;
            }
            set {
                if ((this.kullaniciIdField.Equals(value) != true)) {
                    this.kullaniciIdField = value;
                    this.RaisePropertyChanged("kullaniciId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.idService.soru soru {
            get {
                return this.soruField;
            }
            set {
                if ((object.ReferenceEquals(this.soruField, value) != true)) {
                    this.soruField = value;
                    this.RaisePropertyChanged("soru");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int soruId {
            get {
                return this.soruIdField;
            }
            set {
                if ((this.soruIdField.Equals(value) != true)) {
                    this.soruIdField = value;
                    this.RaisePropertyChanged("soruId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="soru", Namespace="http://schemas.datacontract.org/2004/07/ServiceID.Model")]
    [System.SerializableAttribute()]
    public partial class soru : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string baslikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.idService.cevap[] cevapsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> etiketIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.idService.favori[] favorisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.idService.kategori kategoriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> kategoriIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.idService.kullanici kullaniciField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> kullaniciIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> onayDurumuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.idService.soruEtiket[] soruEtiketsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int soruIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> yayinTarihiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string baslik {
            get {
                return this.baslikField;
            }
            set {
                if ((object.ReferenceEquals(this.baslikField, value) != true)) {
                    this.baslikField = value;
                    this.RaisePropertyChanged("baslik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.idService.cevap[] cevaps {
            get {
                return this.cevapsField;
            }
            set {
                if ((object.ReferenceEquals(this.cevapsField, value) != true)) {
                    this.cevapsField = value;
                    this.RaisePropertyChanged("cevaps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> etiketId {
            get {
                return this.etiketIdField;
            }
            set {
                if ((this.etiketIdField.Equals(value) != true)) {
                    this.etiketIdField = value;
                    this.RaisePropertyChanged("etiketId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.idService.favori[] favoris {
            get {
                return this.favorisField;
            }
            set {
                if ((object.ReferenceEquals(this.favorisField, value) != true)) {
                    this.favorisField = value;
                    this.RaisePropertyChanged("favoris");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.idService.kategori kategori {
            get {
                return this.kategoriField;
            }
            set {
                if ((object.ReferenceEquals(this.kategoriField, value) != true)) {
                    this.kategoriField = value;
                    this.RaisePropertyChanged("kategori");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> kategoriId {
            get {
                return this.kategoriIdField;
            }
            set {
                if ((this.kategoriIdField.Equals(value) != true)) {
                    this.kategoriIdField = value;
                    this.RaisePropertyChanged("kategoriId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.idService.kullanici kullanici {
            get {
                return this.kullaniciField;
            }
            set {
                if ((object.ReferenceEquals(this.kullaniciField, value) != true)) {
                    this.kullaniciField = value;
                    this.RaisePropertyChanged("kullanici");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> kullaniciId {
            get {
                return this.kullaniciIdField;
            }
            set {
                if ((this.kullaniciIdField.Equals(value) != true)) {
                    this.kullaniciIdField = value;
                    this.RaisePropertyChanged("kullaniciId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> onayDurumu {
            get {
                return this.onayDurumuField;
            }
            set {
                if ((this.onayDurumuField.Equals(value) != true)) {
                    this.onayDurumuField = value;
                    this.RaisePropertyChanged("onayDurumu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.idService.soruEtiket[] soruEtikets {
            get {
                return this.soruEtiketsField;
            }
            set {
                if ((object.ReferenceEquals(this.soruEtiketsField, value) != true)) {
                    this.soruEtiketsField = value;
                    this.RaisePropertyChanged("soruEtikets");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int soruId {
            get {
                return this.soruIdField;
            }
            set {
                if ((this.soruIdField.Equals(value) != true)) {
                    this.soruIdField = value;
                    this.RaisePropertyChanged("soruId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> yayinTarihi {
            get {
                return this.yayinTarihiField;
            }
            set {
                if ((this.yayinTarihiField.Equals(value) != true)) {
                    this.yayinTarihiField = value;
                    this.RaisePropertyChanged("yayinTarihi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="yorum", Namespace="http://schemas.datacontract.org/2004/07/ServiceID.Model")]
    [System.SerializableAttribute()]
    public partial class yorum : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.idService.cevap cevapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> cevapIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.idService.kullanici kullaniciField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int kullaniciIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string yorum1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int yorumIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> yorumTarihiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.idService.cevap cevap {
            get {
                return this.cevapField;
            }
            set {
                if ((object.ReferenceEquals(this.cevapField, value) != true)) {
                    this.cevapField = value;
                    this.RaisePropertyChanged("cevap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> cevapId {
            get {
                return this.cevapIdField;
            }
            set {
                if ((this.cevapIdField.Equals(value) != true)) {
                    this.cevapIdField = value;
                    this.RaisePropertyChanged("cevapId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.idService.kullanici kullanici {
            get {
                return this.kullaniciField;
            }
            set {
                if ((object.ReferenceEquals(this.kullaniciField, value) != true)) {
                    this.kullaniciField = value;
                    this.RaisePropertyChanged("kullanici");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int kullaniciId {
            get {
                return this.kullaniciIdField;
            }
            set {
                if ((this.kullaniciIdField.Equals(value) != true)) {
                    this.kullaniciIdField = value;
                    this.RaisePropertyChanged("kullaniciId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string yorum1 {
            get {
                return this.yorum1Field;
            }
            set {
                if ((object.ReferenceEquals(this.yorum1Field, value) != true)) {
                    this.yorum1Field = value;
                    this.RaisePropertyChanged("yorum1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int yorumId {
            get {
                return this.yorumIdField;
            }
            set {
                if ((this.yorumIdField.Equals(value) != true)) {
                    this.yorumIdField = value;
                    this.RaisePropertyChanged("yorumId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> yorumTarihi {
            get {
                return this.yorumTarihiField;
            }
            set {
                if ((this.yorumTarihiField.Equals(value) != true)) {
                    this.yorumTarihiField = value;
                    this.RaisePropertyChanged("yorumTarihi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="kategori", Namespace="http://schemas.datacontract.org/2004/07/ServiceID.Model")]
    [System.SerializableAttribute()]
    public partial class kategori : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int kategorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kategoriAdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.idService.soru[] sorusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int kategorId {
            get {
                return this.kategorIdField;
            }
            set {
                if ((this.kategorIdField.Equals(value) != true)) {
                    this.kategorIdField = value;
                    this.RaisePropertyChanged("kategorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kategoriAd {
            get {
                return this.kategoriAdField;
            }
            set {
                if ((object.ReferenceEquals(this.kategoriAdField, value) != true)) {
                    this.kategoriAdField = value;
                    this.RaisePropertyChanged("kategoriAd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.idService.soru[] sorus {
            get {
                return this.sorusField;
            }
            set {
                if ((object.ReferenceEquals(this.sorusField, value) != true)) {
                    this.sorusField = value;
                    this.RaisePropertyChanged("sorus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="soruEtiket", Namespace="http://schemas.datacontract.org/2004/07/ServiceID.Model")]
    [System.SerializableAttribute()]
    public partial class soruEtiket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.idService.etiket etiketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int etiketIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.idService.soru soruField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int soruEtiketIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int soruIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.idService.etiket etiket {
            get {
                return this.etiketField;
            }
            set {
                if ((object.ReferenceEquals(this.etiketField, value) != true)) {
                    this.etiketField = value;
                    this.RaisePropertyChanged("etiket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int etiketId {
            get {
                return this.etiketIdField;
            }
            set {
                if ((this.etiketIdField.Equals(value) != true)) {
                    this.etiketIdField = value;
                    this.RaisePropertyChanged("etiketId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.idService.soru soru {
            get {
                return this.soruField;
            }
            set {
                if ((object.ReferenceEquals(this.soruField, value) != true)) {
                    this.soruField = value;
                    this.RaisePropertyChanged("soru");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int soruEtiketId {
            get {
                return this.soruEtiketIdField;
            }
            set {
                if ((this.soruEtiketIdField.Equals(value) != true)) {
                    this.soruEtiketIdField = value;
                    this.RaisePropertyChanged("soruEtiketId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int soruId {
            get {
                return this.soruIdField;
            }
            set {
                if ((this.soruIdField.Equals(value) != true)) {
                    this.soruIdField = value;
                    this.RaisePropertyChanged("soruId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="etiket", Namespace="http://schemas.datacontract.org/2004/07/ServiceID.Model")]
    [System.SerializableAttribute()]
    public partial class etiket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string etiketAdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int etiketIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.idService.soruEtiket[] soruEtiketsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string etiketAd {
            get {
                return this.etiketAdField;
            }
            set {
                if ((object.ReferenceEquals(this.etiketAdField, value) != true)) {
                    this.etiketAdField = value;
                    this.RaisePropertyChanged("etiketAd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int etiketId {
            get {
                return this.etiketIdField;
            }
            set {
                if ((this.etiketIdField.Equals(value) != true)) {
                    this.etiketIdField = value;
                    this.RaisePropertyChanged("etiketId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.idService.soruEtiket[] soruEtikets {
            get {
                return this.soruEtiketsField;
            }
            set {
                if ((object.ReferenceEquals(this.soruEtiketsField, value) != true)) {
                    this.soruEtiketsField = value;
                    this.RaisePropertyChanged("soruEtikets");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/ServiceID")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="idService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GirisYap", ReplyAction="http://tempuri.org/IService1/GirisYapResponse")]
        string GirisYap(string kulAd, string sifre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GirisYap", ReplyAction="http://tempuri.org/IService1/GirisYapResponse")]
        System.Threading.Tasks.Task<string> GirisYapAsync(string kulAd, string sifre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KayitOl", ReplyAction="http://tempuri.org/IService1/KayitOlResponse")]
        void KayitOl(clientID.idService.kullanici kul);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KayitOl", ReplyAction="http://tempuri.org/IService1/KayitOlResponse")]
        System.Threading.Tasks.Task KayitOlAsync(clientID.idService.kullanici kul);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        clientID.idService.CompositeType GetDataUsingDataContract(clientID.idService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<clientID.idService.CompositeType> GetDataUsingDataContractAsync(clientID.idService.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : clientID.idService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<clientID.idService.IService1>, clientID.idService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GirisYap(string kulAd, string sifre) {
            return base.Channel.GirisYap(kulAd, sifre);
        }
        
        public System.Threading.Tasks.Task<string> GirisYapAsync(string kulAd, string sifre) {
            return base.Channel.GirisYapAsync(kulAd, sifre);
        }
        
        public void KayitOl(clientID.idService.kullanici kul) {
            base.Channel.KayitOl(kul);
        }
        
        public System.Threading.Tasks.Task KayitOlAsync(clientID.idService.kullanici kul) {
            return base.Channel.KayitOlAsync(kul);
        }
        
        public clientID.idService.CompositeType GetDataUsingDataContract(clientID.idService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<clientID.idService.CompositeType> GetDataUsingDataContractAsync(clientID.idService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
