//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clientID.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="kullanici", Namespace="http://schemas.datacontract.org/2004/07/serviceID.Model")]
    [System.SerializableAttribute()]
    public partial class kullanici : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.ServiceReference1.begeni[] begenisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.ServiceReference1.cevap[] cevapsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.ServiceReference1.favori[] favorisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kullaniciAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int kullaniciIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sifreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.ServiceReference1.soru[] sorusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.ServiceReference1.yorum[] yorumsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.ServiceReference1.begeni[] begenis {
            get {
                return this.begenisField;
            }
            set {
                if ((object.ReferenceEquals(this.begenisField, value) != true)) {
                    this.begenisField = value;
                    this.RaisePropertyChanged("begenis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.ServiceReference1.cevap[] cevaps {
            get {
                return this.cevapsField;
            }
            set {
                if ((object.ReferenceEquals(this.cevapsField, value) != true)) {
                    this.cevapsField = value;
                    this.RaisePropertyChanged("cevaps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.ServiceReference1.favori[] favoris {
            get {
                return this.favorisField;
            }
            set {
                if ((object.ReferenceEquals(this.favorisField, value) != true)) {
                    this.favorisField = value;
                    this.RaisePropertyChanged("favoris");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kullaniciAdi {
            get {
                return this.kullaniciAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.kullaniciAdiField, value) != true)) {
                    this.kullaniciAdiField = value;
                    this.RaisePropertyChanged("kullaniciAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int kullaniciId {
            get {
                return this.kullaniciIdField;
            }
            set {
                if ((this.kullaniciIdField.Equals(value) != true)) {
                    this.kullaniciIdField = value;
                    this.RaisePropertyChanged("kullaniciId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sifre {
            get {
                return this.sifreField;
            }
            set {
                if ((object.ReferenceEquals(this.sifreField, value) != true)) {
                    this.sifreField = value;
                    this.RaisePropertyChanged("sifre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.ServiceReference1.soru[] sorus {
            get {
                return this.sorusField;
            }
            set {
                if ((object.ReferenceEquals(this.sorusField, value) != true)) {
                    this.sorusField = value;
                    this.RaisePropertyChanged("sorus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.ServiceReference1.yorum[] yorums {
            get {
                return this.yorumsField;
            }
            set {
                if ((object.ReferenceEquals(this.yorumsField, value) != true)) {
                    this.yorumsField = value;
                    this.RaisePropertyChanged("yorums");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="begeni", Namespace="http://schemas.datacontract.org/2004/07/serviceID.Model")]
    [System.SerializableAttribute()]
    public partial class begeni : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int begeniIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> begeniTuruIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.ServiceReference1.cevap cevapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> cevapIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.ServiceReference1.kullanici kullaniciField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int kullaniciIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int begeniId {
            get {
                return this.begeniIdField;
            }
            set {
                if ((this.begeniIdField.Equals(value) != true)) {
                    this.begeniIdField = value;
                    this.RaisePropertyChanged("begeniId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> begeniTuruId {
            get {
                return this.begeniTuruIdField;
            }
            set {
                if ((this.begeniTuruIdField.Equals(value) != true)) {
                    this.begeniTuruIdField = value;
                    this.RaisePropertyChanged("begeniTuruId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.ServiceReference1.cevap cevap {
            get {
                return this.cevapField;
            }
            set {
                if ((object.ReferenceEquals(this.cevapField, value) != true)) {
                    this.cevapField = value;
                    this.RaisePropertyChanged("cevap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> cevapId {
            get {
                return this.cevapIdField;
            }
            set {
                if ((this.cevapIdField.Equals(value) != true)) {
                    this.cevapIdField = value;
                    this.RaisePropertyChanged("cevapId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.ServiceReference1.kullanici kullanici {
            get {
                return this.kullaniciField;
            }
            set {
                if ((object.ReferenceEquals(this.kullaniciField, value) != true)) {
                    this.kullaniciField = value;
                    this.RaisePropertyChanged("kullanici");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int kullaniciId {
            get {
                return this.kullaniciIdField;
            }
            set {
                if ((this.kullaniciIdField.Equals(value) != true)) {
                    this.kullaniciIdField = value;
                    this.RaisePropertyChanged("kullaniciId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="cevap", Namespace="http://schemas.datacontract.org/2004/07/serviceID.Model")]
    [System.SerializableAttribute()]
    public partial class cevap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.ServiceReference1.begeni[] begenisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cevap1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cevapIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> cevapTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.ServiceReference1.kullanici kullaniciField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int kullaniciIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.ServiceReference1.soru soruField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int soruIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.ServiceReference1.yorum[] yorumsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.ServiceReference1.begeni[] begenis {
            get {
                return this.begenisField;
            }
            set {
                if ((object.ReferenceEquals(this.begenisField, value) != true)) {
                    this.begenisField = value;
                    this.RaisePropertyChanged("begenis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cevap1 {
            get {
                return this.cevap1Field;
            }
            set {
                if ((object.ReferenceEquals(this.cevap1Field, value) != true)) {
                    this.cevap1Field = value;
                    this.RaisePropertyChanged("cevap1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cevapId {
            get {
                return this.cevapIdField;
            }
            set {
                if ((this.cevapIdField.Equals(value) != true)) {
                    this.cevapIdField = value;
                    this.RaisePropertyChanged("cevapId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> cevapTarihi {
            get {
                return this.cevapTarihiField;
            }
            set {
                if ((this.cevapTarihiField.Equals(value) != true)) {
                    this.cevapTarihiField = value;
                    this.RaisePropertyChanged("cevapTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.ServiceReference1.kullanici kullanici {
            get {
                return this.kullaniciField;
            }
            set {
                if ((object.ReferenceEquals(this.kullaniciField, value) != true)) {
                    this.kullaniciField = value;
                    this.RaisePropertyChanged("kullanici");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int kullaniciId {
            get {
                return this.kullaniciIdField;
            }
            set {
                if ((this.kullaniciIdField.Equals(value) != true)) {
                    this.kullaniciIdField = value;
                    this.RaisePropertyChanged("kullaniciId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.ServiceReference1.soru soru {
            get {
                return this.soruField;
            }
            set {
                if ((object.ReferenceEquals(this.soruField, value) != true)) {
                    this.soruField = value;
                    this.RaisePropertyChanged("soru");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int soruId {
            get {
                return this.soruIdField;
            }
            set {
                if ((this.soruIdField.Equals(value) != true)) {
                    this.soruIdField = value;
                    this.RaisePropertyChanged("soruId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.ServiceReference1.yorum[] yorums {
            get {
                return this.yorumsField;
            }
            set {
                if ((object.ReferenceEquals(this.yorumsField, value) != true)) {
                    this.yorumsField = value;
                    this.RaisePropertyChanged("yorums");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="favori", Namespace="http://schemas.datacontract.org/2004/07/serviceID.Model")]
    [System.SerializableAttribute()]
    public partial class favori : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int favoriIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.ServiceReference1.kullanici kullaniciField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int kullaniciIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.ServiceReference1.soru soruField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int soruIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int favoriId {
            get {
                return this.favoriIdField;
            }
            set {
                if ((this.favoriIdField.Equals(value) != true)) {
                    this.favoriIdField = value;
                    this.RaisePropertyChanged("favoriId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.ServiceReference1.kullanici kullanici {
            get {
                return this.kullaniciField;
            }
            set {
                if ((object.ReferenceEquals(this.kullaniciField, value) != true)) {
                    this.kullaniciField = value;
                    this.RaisePropertyChanged("kullanici");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int kullaniciId {
            get {
                return this.kullaniciIdField;
            }
            set {
                if ((this.kullaniciIdField.Equals(value) != true)) {
                    this.kullaniciIdField = value;
                    this.RaisePropertyChanged("kullaniciId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.ServiceReference1.soru soru {
            get {
                return this.soruField;
            }
            set {
                if ((object.ReferenceEquals(this.soruField, value) != true)) {
                    this.soruField = value;
                    this.RaisePropertyChanged("soru");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int soruId {
            get {
                return this.soruIdField;
            }
            set {
                if ((this.soruIdField.Equals(value) != true)) {
                    this.soruIdField = value;
                    this.RaisePropertyChanged("soruId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="soru", Namespace="http://schemas.datacontract.org/2004/07/serviceID.Model")]
    [System.SerializableAttribute()]
    public partial class soru : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string baslikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.ServiceReference1.cevap[] cevapsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> etiketIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.ServiceReference1.favori[] favorisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.ServiceReference1.kategori kategoriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> kategoriIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.ServiceReference1.kullanici kullaniciField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> kullaniciIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> onayDurumuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.ServiceReference1.soruEtiket[] soruEtiketsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string soruIcerikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int soruIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> yayinTarihiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string baslik {
            get {
                return this.baslikField;
            }
            set {
                if ((object.ReferenceEquals(this.baslikField, value) != true)) {
                    this.baslikField = value;
                    this.RaisePropertyChanged("baslik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.ServiceReference1.cevap[] cevaps {
            get {
                return this.cevapsField;
            }
            set {
                if ((object.ReferenceEquals(this.cevapsField, value) != true)) {
                    this.cevapsField = value;
                    this.RaisePropertyChanged("cevaps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> etiketId {
            get {
                return this.etiketIdField;
            }
            set {
                if ((this.etiketIdField.Equals(value) != true)) {
                    this.etiketIdField = value;
                    this.RaisePropertyChanged("etiketId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.ServiceReference1.favori[] favoris {
            get {
                return this.favorisField;
            }
            set {
                if ((object.ReferenceEquals(this.favorisField, value) != true)) {
                    this.favorisField = value;
                    this.RaisePropertyChanged("favoris");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.ServiceReference1.kategori kategori {
            get {
                return this.kategoriField;
            }
            set {
                if ((object.ReferenceEquals(this.kategoriField, value) != true)) {
                    this.kategoriField = value;
                    this.RaisePropertyChanged("kategori");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> kategoriId {
            get {
                return this.kategoriIdField;
            }
            set {
                if ((this.kategoriIdField.Equals(value) != true)) {
                    this.kategoriIdField = value;
                    this.RaisePropertyChanged("kategoriId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.ServiceReference1.kullanici kullanici {
            get {
                return this.kullaniciField;
            }
            set {
                if ((object.ReferenceEquals(this.kullaniciField, value) != true)) {
                    this.kullaniciField = value;
                    this.RaisePropertyChanged("kullanici");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> kullaniciId {
            get {
                return this.kullaniciIdField;
            }
            set {
                if ((this.kullaniciIdField.Equals(value) != true)) {
                    this.kullaniciIdField = value;
                    this.RaisePropertyChanged("kullaniciId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> onayDurumu {
            get {
                return this.onayDurumuField;
            }
            set {
                if ((this.onayDurumuField.Equals(value) != true)) {
                    this.onayDurumuField = value;
                    this.RaisePropertyChanged("onayDurumu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.ServiceReference1.soruEtiket[] soruEtikets {
            get {
                return this.soruEtiketsField;
            }
            set {
                if ((object.ReferenceEquals(this.soruEtiketsField, value) != true)) {
                    this.soruEtiketsField = value;
                    this.RaisePropertyChanged("soruEtikets");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string soruIcerik {
            get {
                return this.soruIcerikField;
            }
            set {
                if ((object.ReferenceEquals(this.soruIcerikField, value) != true)) {
                    this.soruIcerikField = value;
                    this.RaisePropertyChanged("soruIcerik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int soruId {
            get {
                return this.soruIdField;
            }
            set {
                if ((this.soruIdField.Equals(value) != true)) {
                    this.soruIdField = value;
                    this.RaisePropertyChanged("soruId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> yayinTarihi {
            get {
                return this.yayinTarihiField;
            }
            set {
                if ((this.yayinTarihiField.Equals(value) != true)) {
                    this.yayinTarihiField = value;
                    this.RaisePropertyChanged("yayinTarihi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="yorum", Namespace="http://schemas.datacontract.org/2004/07/serviceID.Model")]
    [System.SerializableAttribute()]
    public partial class yorum : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.ServiceReference1.cevap cevapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> cevapIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.ServiceReference1.kullanici kullaniciField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int kullaniciIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string yorum1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int yorumIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> yorumTarihiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.ServiceReference1.cevap cevap {
            get {
                return this.cevapField;
            }
            set {
                if ((object.ReferenceEquals(this.cevapField, value) != true)) {
                    this.cevapField = value;
                    this.RaisePropertyChanged("cevap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> cevapId {
            get {
                return this.cevapIdField;
            }
            set {
                if ((this.cevapIdField.Equals(value) != true)) {
                    this.cevapIdField = value;
                    this.RaisePropertyChanged("cevapId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.ServiceReference1.kullanici kullanici {
            get {
                return this.kullaniciField;
            }
            set {
                if ((object.ReferenceEquals(this.kullaniciField, value) != true)) {
                    this.kullaniciField = value;
                    this.RaisePropertyChanged("kullanici");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int kullaniciId {
            get {
                return this.kullaniciIdField;
            }
            set {
                if ((this.kullaniciIdField.Equals(value) != true)) {
                    this.kullaniciIdField = value;
                    this.RaisePropertyChanged("kullaniciId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string yorum1 {
            get {
                return this.yorum1Field;
            }
            set {
                if ((object.ReferenceEquals(this.yorum1Field, value) != true)) {
                    this.yorum1Field = value;
                    this.RaisePropertyChanged("yorum1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int yorumId {
            get {
                return this.yorumIdField;
            }
            set {
                if ((this.yorumIdField.Equals(value) != true)) {
                    this.yorumIdField = value;
                    this.RaisePropertyChanged("yorumId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> yorumTarihi {
            get {
                return this.yorumTarihiField;
            }
            set {
                if ((this.yorumTarihiField.Equals(value) != true)) {
                    this.yorumTarihiField = value;
                    this.RaisePropertyChanged("yorumTarihi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="kategori", Namespace="http://schemas.datacontract.org/2004/07/serviceID.Model")]
    [System.SerializableAttribute()]
    public partial class kategori : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int kategorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kategoriAdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.ServiceReference1.soru[] sorusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int kategorId {
            get {
                return this.kategorIdField;
            }
            set {
                if ((this.kategorIdField.Equals(value) != true)) {
                    this.kategorIdField = value;
                    this.RaisePropertyChanged("kategorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kategoriAd {
            get {
                return this.kategoriAdField;
            }
            set {
                if ((object.ReferenceEquals(this.kategoriAdField, value) != true)) {
                    this.kategoriAdField = value;
                    this.RaisePropertyChanged("kategoriAd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.ServiceReference1.soru[] sorus {
            get {
                return this.sorusField;
            }
            set {
                if ((object.ReferenceEquals(this.sorusField, value) != true)) {
                    this.sorusField = value;
                    this.RaisePropertyChanged("sorus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="soruEtiket", Namespace="http://schemas.datacontract.org/2004/07/serviceID.Model")]
    [System.SerializableAttribute()]
    public partial class soruEtiket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.ServiceReference1.etiket etiketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int etiketIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.ServiceReference1.soru soruField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int soruEtiketIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int soruIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.ServiceReference1.etiket etiket {
            get {
                return this.etiketField;
            }
            set {
                if ((object.ReferenceEquals(this.etiketField, value) != true)) {
                    this.etiketField = value;
                    this.RaisePropertyChanged("etiket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int etiketId {
            get {
                return this.etiketIdField;
            }
            set {
                if ((this.etiketIdField.Equals(value) != true)) {
                    this.etiketIdField = value;
                    this.RaisePropertyChanged("etiketId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.ServiceReference1.soru soru {
            get {
                return this.soruField;
            }
            set {
                if ((object.ReferenceEquals(this.soruField, value) != true)) {
                    this.soruField = value;
                    this.RaisePropertyChanged("soru");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int soruEtiketId {
            get {
                return this.soruEtiketIdField;
            }
            set {
                if ((this.soruEtiketIdField.Equals(value) != true)) {
                    this.soruEtiketIdField = value;
                    this.RaisePropertyChanged("soruEtiketId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int soruId {
            get {
                return this.soruIdField;
            }
            set {
                if ((this.soruIdField.Equals(value) != true)) {
                    this.soruIdField = value;
                    this.RaisePropertyChanged("soruId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="etiket", Namespace="http://schemas.datacontract.org/2004/07/serviceID.Model")]
    [System.SerializableAttribute()]
    public partial class etiket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string etiketAdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int etiketIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private clientID.ServiceReference1.soruEtiket[] soruEtiketsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string etiketAd {
            get {
                return this.etiketAdField;
            }
            set {
                if ((object.ReferenceEquals(this.etiketAdField, value) != true)) {
                    this.etiketAdField = value;
                    this.RaisePropertyChanged("etiketAd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int etiketId {
            get {
                return this.etiketIdField;
            }
            set {
                if ((this.etiketIdField.Equals(value) != true)) {
                    this.etiketIdField = value;
                    this.RaisePropertyChanged("etiketId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public clientID.ServiceReference1.soruEtiket[] soruEtikets {
            get {
                return this.soruEtiketsField;
            }
            set {
                if ((object.ReferenceEquals(this.soruEtiketsField, value) != true)) {
                    this.soruEtiketsField = value;
                    this.RaisePropertyChanged("soruEtikets");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="soruView", Namespace="http://schemas.datacontract.org/2004/07/serviceID.Model.ViewModel")]
    [System.SerializableAttribute()]
    public partial class soruView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string baslikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> etiketIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> kategoriIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> kullaniciIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> onayDurumuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string soruIcerikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int soruIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> yayinTarihiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string baslik {
            get {
                return this.baslikField;
            }
            set {
                if ((object.ReferenceEquals(this.baslikField, value) != true)) {
                    this.baslikField = value;
                    this.RaisePropertyChanged("baslik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> etiketId {
            get {
                return this.etiketIdField;
            }
            set {
                if ((this.etiketIdField.Equals(value) != true)) {
                    this.etiketIdField = value;
                    this.RaisePropertyChanged("etiketId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> kategoriId {
            get {
                return this.kategoriIdField;
            }
            set {
                if ((this.kategoriIdField.Equals(value) != true)) {
                    this.kategoriIdField = value;
                    this.RaisePropertyChanged("kategoriId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> kullaniciId {
            get {
                return this.kullaniciIdField;
            }
            set {
                if ((this.kullaniciIdField.Equals(value) != true)) {
                    this.kullaniciIdField = value;
                    this.RaisePropertyChanged("kullaniciId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> onayDurumu {
            get {
                return this.onayDurumuField;
            }
            set {
                if ((this.onayDurumuField.Equals(value) != true)) {
                    this.onayDurumuField = value;
                    this.RaisePropertyChanged("onayDurumu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string soruIcerik {
            get {
                return this.soruIcerikField;
            }
            set {
                if ((object.ReferenceEquals(this.soruIcerikField, value) != true)) {
                    this.soruIcerikField = value;
                    this.RaisePropertyChanged("soruIcerik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int soruId {
            get {
                return this.soruIdField;
            }
            set {
                if ((this.soruIdField.Equals(value) != true)) {
                    this.soruIdField = value;
                    this.RaisePropertyChanged("soruId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> yayinTarihi {
            get {
                return this.yayinTarihiField;
            }
            set {
                if ((this.yayinTarihiField.Equals(value) != true)) {
                    this.yayinTarihiField = value;
                    this.RaisePropertyChanged("yayinTarihi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GirisYap", ReplyAction="http://tempuri.org/IService1/GirisYapResponse")]
        int GirisYap(clientID.ServiceReference1.kullanici kullanici);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GirisYap", ReplyAction="http://tempuri.org/IService1/GirisYapResponse")]
        System.Threading.Tasks.Task<int> GirisYapAsync(clientID.ServiceReference1.kullanici kullanici);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KayitOl", ReplyAction="http://tempuri.org/IService1/KayitOlResponse")]
        int KayitOl(clientID.ServiceReference1.kullanici kul);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KayitOl", ReplyAction="http://tempuri.org/IService1/KayitOlResponse")]
        System.Threading.Tasks.Task<int> KayitOlAsync(clientID.ServiceReference1.kullanici kul);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SoruEkle", ReplyAction="http://tempuri.org/IService1/SoruEkleResponse")]
        bool SoruEkle(clientID.ServiceReference1.soru soru);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SoruEkle", ReplyAction="http://tempuri.org/IService1/SoruEkleResponse")]
        System.Threading.Tasks.Task<bool> SoruEkleAsync(clientID.ServiceReference1.soru soru);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KategoriEkle", ReplyAction="http://tempuri.org/IService1/KategoriEkleResponse")]
        bool KategoriEkle(clientID.ServiceReference1.kategori kategori);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KategoriEkle", ReplyAction="http://tempuri.org/IService1/KategoriEkleResponse")]
        System.Threading.Tasks.Task<bool> KategoriEkleAsync(clientID.ServiceReference1.kategori kategori);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EtiketEkle", ReplyAction="http://tempuri.org/IService1/EtiketEkleResponse")]
        bool EtiketEkle(clientID.ServiceReference1.etiket etiket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EtiketEkle", ReplyAction="http://tempuri.org/IService1/EtiketEkleResponse")]
        System.Threading.Tasks.Task<bool> EtiketEkleAsync(clientID.ServiceReference1.etiket etiket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SoruyaCevapYaz", ReplyAction="http://tempuri.org/IService1/SoruyaCevapYazResponse")]
        bool SoruyaCevapYaz(clientID.ServiceReference1.cevap cevap);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SoruyaCevapYaz", ReplyAction="http://tempuri.org/IService1/SoruyaCevapYazResponse")]
        System.Threading.Tasks.Task<bool> SoruyaCevapYazAsync(clientID.ServiceReference1.cevap cevap);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CevabaYorumYaz", ReplyAction="http://tempuri.org/IService1/CevabaYorumYazResponse")]
        bool CevabaYorumYaz(clientID.ServiceReference1.yorum yorum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CevabaYorumYaz", ReplyAction="http://tempuri.org/IService1/CevabaYorumYazResponse")]
        System.Threading.Tasks.Task<bool> CevabaYorumYazAsync(clientID.ServiceReference1.yorum yorum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SoruFavoriEkle", ReplyAction="http://tempuri.org/IService1/SoruFavoriEkleResponse")]
        bool SoruFavoriEkle(clientID.ServiceReference1.favori fav);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SoruFavoriEkle", ReplyAction="http://tempuri.org/IService1/SoruFavoriEkleResponse")]
        System.Threading.Tasks.Task<bool> SoruFavoriEkleAsync(clientID.ServiceReference1.favori fav);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Sorular", ReplyAction="http://tempuri.org/IService1/SorularResponse")]
        clientID.ServiceReference1.soruView[] Sorular();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Sorular", ReplyAction="http://tempuri.org/IService1/SorularResponse")]
        System.Threading.Tasks.Task<clientID.ServiceReference1.soruView[]> SorularAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SoruAra", ReplyAction="http://tempuri.org/IService1/SoruAraResponse")]
        clientID.ServiceReference1.soru SoruAra(string soruBaslik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SoruAra", ReplyAction="http://tempuri.org/IService1/SoruAraResponse")]
        System.Threading.Tasks.Task<clientID.ServiceReference1.soru> SoruAraAsync(string soruBaslik);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : clientID.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<clientID.ServiceReference1.IService1>, clientID.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public int GirisYap(clientID.ServiceReference1.kullanici kullanici) {
            return base.Channel.GirisYap(kullanici);
        }
        
        public System.Threading.Tasks.Task<int> GirisYapAsync(clientID.ServiceReference1.kullanici kullanici) {
            return base.Channel.GirisYapAsync(kullanici);
        }
        
        public int KayitOl(clientID.ServiceReference1.kullanici kul) {
            return base.Channel.KayitOl(kul);
        }
        
        public System.Threading.Tasks.Task<int> KayitOlAsync(clientID.ServiceReference1.kullanici kul) {
            return base.Channel.KayitOlAsync(kul);
        }
        
        public bool SoruEkle(clientID.ServiceReference1.soru soru) {
            return base.Channel.SoruEkle(soru);
        }
        
        public System.Threading.Tasks.Task<bool> SoruEkleAsync(clientID.ServiceReference1.soru soru) {
            return base.Channel.SoruEkleAsync(soru);
        }
        
        public bool KategoriEkle(clientID.ServiceReference1.kategori kategori) {
            return base.Channel.KategoriEkle(kategori);
        }
        
        public System.Threading.Tasks.Task<bool> KategoriEkleAsync(clientID.ServiceReference1.kategori kategori) {
            return base.Channel.KategoriEkleAsync(kategori);
        }
        
        public bool EtiketEkle(clientID.ServiceReference1.etiket etiket) {
            return base.Channel.EtiketEkle(etiket);
        }
        
        public System.Threading.Tasks.Task<bool> EtiketEkleAsync(clientID.ServiceReference1.etiket etiket) {
            return base.Channel.EtiketEkleAsync(etiket);
        }
        
        public bool SoruyaCevapYaz(clientID.ServiceReference1.cevap cevap) {
            return base.Channel.SoruyaCevapYaz(cevap);
        }
        
        public System.Threading.Tasks.Task<bool> SoruyaCevapYazAsync(clientID.ServiceReference1.cevap cevap) {
            return base.Channel.SoruyaCevapYazAsync(cevap);
        }
        
        public bool CevabaYorumYaz(clientID.ServiceReference1.yorum yorum) {
            return base.Channel.CevabaYorumYaz(yorum);
        }
        
        public System.Threading.Tasks.Task<bool> CevabaYorumYazAsync(clientID.ServiceReference1.yorum yorum) {
            return base.Channel.CevabaYorumYazAsync(yorum);
        }
        
        public bool SoruFavoriEkle(clientID.ServiceReference1.favori fav) {
            return base.Channel.SoruFavoriEkle(fav);
        }
        
        public System.Threading.Tasks.Task<bool> SoruFavoriEkleAsync(clientID.ServiceReference1.favori fav) {
            return base.Channel.SoruFavoriEkleAsync(fav);
        }
        
        public clientID.ServiceReference1.soruView[] Sorular() {
            return base.Channel.Sorular();
        }
        
        public System.Threading.Tasks.Task<clientID.ServiceReference1.soruView[]> SorularAsync() {
            return base.Channel.SorularAsync();
        }
        
        public clientID.ServiceReference1.soru SoruAra(string soruBaslik) {
            return base.Channel.SoruAra(soruBaslik);
        }
        
        public System.Threading.Tasks.Task<clientID.ServiceReference1.soru> SoruAraAsync(string soruBaslik) {
            return base.Channel.SoruAraAsync(soruBaslik);
        }
    }
}
